name: Test Ubuntu

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
         webhook: ${{ secrets.YOUR_DISCORD_WEBHOOK_URL }}
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Submodule init
      run: git submodule init
    - name: Submodule update
      run: git submodule update
    - name: Restore dependencies
      run: dotnet restore "RhubarbVR"
    - name: Build
      run: dotnet build "RhubarbVR" --no-restore /p:Configuration=Release /p:Platform="x64"
    - name: Test
      run: dotnet test "RhubarbEngineTests" --no-restore --verbosity normal /p:Configuration=Release /p:Platform="x64"

